import 'package:share_plus/share_plus.dart';

class ShareService {
  static Future<void> shareExcuse({
    required String category,
    required String excuse,
  }) async {
    final String text = "My excuse for $category: \"$excuse\" 😅 — Generated by Smart Excuse Generator";
    await Share.share(text);
  }
}
